[package]
name = "osu_api_internal_derive"
version = "0.1.0"
authors = ["ekrctb <ekrctb@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.42", features = ["full"] }
quote = "0.6.13"
proc-macro2 = { version = "0.4.30", features = ["nightly"] }
